name: Terraform Deployment & Security Scan

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - prod
  workflow_dispatch:

jobs:
  security-scan:
    name: Run tfsec Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go (required for tfsec)
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec .

  terraform-deploy:
    name: Terraform Deployment
    needs: security-scan
    runs-on: ubuntu-latest
    env:
      TF_VAR_webserver_count: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/staging' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
