name: "Terraform tfsec Scan - Staging"

on:
  push:
    branches:
      - staging
    paths:
      - network/**
      - webserver/**
      - modules/**
  pull_request:
    branches:
      - staging
    paths:
      - network/**
      - webserver/**
      - modules/**

jobs:
  tfsec:
    name: Run tfsec on all Terraform folders
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [network, webserver]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec ./${{ matrix.folder }}
